x-networks: &default-network
  networks:
    - otel
services:
  oteltester:
    image: oteltester
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "5270:8080"
    <<: *default-network
    environment:
      - OTEL_SERVICE_NAME=OtelTester
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://oteltester.dashboard:18889
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - oteltester.dashboard
      - oteltester.seq
  oteltester.dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - "18888:18888"
    <<: *default-network
    environment:
      # This should be local only
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
  oteltester.seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    <<: *default-network
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq:/data
networks:
  otel:
volumes:
  seq:
